0.9.4-prerelease2
united-manufacturing-hub/united-manufacturing-hub pull request #1096
Opened 2022-05-13 15:23 UTC by Scarjit

This pr tracks the progress to 0.9.4-prerelease2

2022-05-13 15:27 UTC, Scarjit commented
Testing is blocked, due to my being unable to find the k3os usb stick :(

2022-05-16 08:50 UTC, Scarjit commented
Checks:

 - [X] Installs without errors
 - [X] All default services start
 - [ ] Enabling barcode reader works
 - [X] Enabling datainput works
 - [X] Enabling barcodereader works
 - [X] Enabling cameraconnect works

2022-05-17 13:30 UTC, JeremyTheocharis requested changes

2022-05-17 13:30 UTC, JeremyTheocharis commented on docs/static/examples/development.yaml
> +      if ! helm install united-manufacturing-hub united-manufacturing-hub/united-manufacturing-hub --values "/home/rancher/configs/united-manufacturing-hub-development.yaml" --set serialNumber=$(host
here also

2022-05-17 14:37 UTC, JeremyTheocharis requested changes

2022-05-17 14:37 UTC, JeremyTheocharis commented on docs/static/examples/development.yaml
> +          enabled: true
as discussed

2022-05-17 14:37 UTC, JeremyTheocharis commented on docs/static/examples/development.yaml
> +        enabled: true
as discussed

2022-05-17 14:37 UTC, JeremyTheocharis commented on docs/static/examples/development.yaml
> +          enabled: true
as discussed

2022-05-17 14:37 UTC, JeremyTheocharis commented on docs/static/examples/development.yaml
> +          defaultFlows: true
as discussed

2022-05-17 17:06 UTC, JeremyTheocharis approved these changes

2022-05-17 20:37 UTC, Scarjit commented
@JeremyTheocharis requires manual merge, kafka dev private keys kill gitguardian

2022-05-18 12:23 UTC, merged