feat: changed prefixes
united-manufacturing-hub/united-manufacturing-hub pull request #1139
Opened 2022-06-01 07:24 UTC by Scarjit

# Description

This pr fixes an issue, where assets are not created

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [ ] Asset creation works on AutoDeploy

**Test Configuration**:
* Kubernetes Version: v1.21.5+k3s2
* Helm Version: v3.9.0
* Hardware: CPU: 4xkvm64 (aes), SeaBIOS, i440fx, 8GB Memory, 10GB Disk

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked that my issue complies with the [Contributing guidelines](https://github.com/united-manufacturing-hub/united-manufacturing-hub/blob/main/CONTRIBUTING.md)

2022-06-02 20:45 UTC, JeremyTheocharis requested changes

2022-06-02 20:45 UTC, JeremyTheocharis commented on docs/static/examples/development.yaml
> +        tag: "latest"
Please remove

2022-06-02 20:45 UTC, JeremyTheocharis commented on deployment/united-manufacturing-hub/templates/timescaledb/configmap.yaml
> +        assetID TEXT NOT NULL,
Add tutorial for migrating!

2022-06-03 08:14 UTC, Scarjit commented on deployment/united-manufacturing-hub/templates/timescaledb/configmap.yaml
> +        assetID TEXT NOT NULL,
Added notion article

2022-06-03 12:24 UTC, merged