feat: changed style to be inline with other services
united-manufacturing-hub/united-manufacturing-hub pull request #1158
Opened 2022-06-07 09:21 UTC by Scarjit

# Description

This pr changes the style of the values.yaml file for mqttbridge, sensorconnect, cameraconnect to match the style of the other services

Fixes #1157 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings
- [X] I have checked that my issue complies with the [Contributing guidelines](https://github.com/united-manufacturing-hub/united-manufacturing-hub/blob/main/CONTRIBUTING.md)

2022-06-07 12:06 UTC, JeremyTheocharis requested changes

2022-06-07 12:06 UTC, JeremyTheocharis commented on deployment/united-manufacturing-hub/values.yaml
>  mqttbridge:
THis requires again an tutorial on upgrading

2022-09-30 07:15 UTC, JeremyTheocharis reviewed
Are you sure this is not a breaking change? Cant they not any backwards compatibility issues?

2022-10-04 13:12 UTC, JeremyTheocharis commented
> Are you sure this is not a breaking change? Cant they not any backwards compatibility issues?

@Scarjit Reminder that this is still open

2022-10-04 13:17 UTC, Scarjit commented
@JeremyTheocharis Unsure if this is breaking.

2023-01-20 14:45 UTC, closed without merging