feat: added minimal and reduced overall size
united-manufacturing-hub/united-manufacturing-hub pull request #1233
Opened 2022-08-30 11:55 UTC by JeremyTheocharis

additionally, added topicmap

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Kubernetes Version: 
* Helm Version:
* Hardware:

# Checklist:

- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding changes to the changelog (if needed).
- [ ] I have made corresponding notices to the upgrade instructions (if needed)

# Changelog changes

Enter here your text for the changelog (or fill it out directly in Notion if you are internal)

# Upgrade instructions

Enter here your tutorial for upgrading from a previous version (or fill it out directly in Notion if you are internal). This can include changing the values.yaml, database migrations or other manual changes that are not automatically handled by the PR

2022-09-20 16:25 UTC, JeremyTheocharis commented
Please take over @DaruZero!

2022-09-27 13:07 UTC, DaruZero approved these changes
develpopment.yaml tested in a virtual machine with 4 CPUs and 8GB of RAM. Deployed successfully and working prorperly. ACL correctly disabled by default

2022-09-27 14:22 UTC, Scarjit requested changes
Why are there changes to our PKI structure in an yml change ?

2022-09-27 14:26 UTC, Scarjit approved these changes

2022-09-27 14:30 UTC, merged