Feat/1289/update helm values
united-manufacturing-hub/united-manufacturing-hub pull request #1291
Opened 2022-10-04 11:43 UTC by DaruZero

# Description

This PR updates the `values.yaml` file with the content of the `development-minimal.yaml` file, and the `development.yaml` with just the startup script
This way we have a default minimal configuration with the option to customize thel deployment using the new `development.yaml` file.

Fixes #1289 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Kubernetes Version: 
* Helm Version:
* Hardware:

# Checklist:

- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding changes to the changelog (if needed).
- [ ] I have made corresponding notices to the upgrade instructions (if needed)

# Changelog changes

# Upgrade instructions

2022-10-04 13:11 UTC, JeremyTheocharis requested changes

2022-10-04 13:11 UTC, JeremyTheocharis commented on docs/static/deployments/development.yaml
> +        replicaCount: 3
lets use the original replicas of the development-minimal  (which is 1)

2022-10-04 13:11 UTC, JeremyTheocharis commented on docs/static/deployments/development.yaml
> +        replicaCount: 3
also all limits and requests

2022-10-04 15:55 UTC, JeremyTheocharis requested changes

2022-10-04 15:55 UTC, JeremyTheocharis commented on deployment/united-manufacturing-hub/values.yaml
> -    - name: DOCKER_VERNEMQ_LISTENER__TCP__ALLOWED_PROTOCOL_VERSIONS
this value is actually important for the MQTT simulator.

2022-10-04 16:39 UTC, JeremyTheocharis commented
I need to rebase this on the v0.9.6-prerelease1 branch. A change of the values.yaml and development.yaml can only be executed at the same time with a new version release as it would break otherwise the existing installation process.

2022-10-05 10:57 UTC, Scarjit commented
@JeremyTheocharis Can you re-review this, so i can prepare the 0.9.6-pr1 release ?

2022-10-05 11:36 UTC, JeremyTheocharis approved these changes

2022-10-05 11:36 UTC, merged