Kafka topic updater
united-manufacturing-hub/united-manufacturing-hub pull request #1316
Opened 2022-10-14 13:39 UTC by Sphingobium

DO NOT MERGE

2022-10-20 09:00 UTC, DaruZero requested changes

2022-10-24 09:46 UTC, Scarjit requested changes

2022-10-24 09:46 UTC, Scarjit commented on deployment/united-manufacturing-hub/values.yaml
> +    area: area
Change these to DefaultArea, DefaultProductionLine to match our placeholders in factoryinsight

2022-10-24 09:46 UTC, Scarjit commented on deployment/united-manufacturing-hub/values.yaml
> +    enterprise: enterprise
default enterprise should be factoryinsight

2022-10-24 09:46 UTC, Scarjit commented on deployment/united-manufacturing-hub/values.yaml
> +    site: site
testLocation

2022-10-24 09:46 UTC, Scarjit commented on deployment/united-manufacturing-hub/values.yaml
> +    workcell: workcell
testMachine

2022-10-24 09:46 UTC, Scarjit commented on deployment/united-manufacturing-hub/values.yaml
> +    area: area
![image](https://user-images.githubusercontent.com/6317420/197496921-70a15e97-07d7-4e1e-82ad-c01364cb56d1.png)

2022-10-24 09:46 UTC, Scarjit commented on golang/pkg/datamodel/messageStructs.go
> +type Productadd struct {
ProductAdd

2022-10-24 09:46 UTC, Scarjit commented on golang/pkg/datamodel/messageStructs.go
> +type Stateactivity struct {
StateActivity

2022-10-24 09:46 UTC, Scarjit commented on golang/pkg/datamodel/messageStructs.go
> +type Statereason struct {
StateReason (same capitalization for the ones below)

2022-10-25 08:41 UTC, Scarjit approved these changes

2022-10-26 09:39 UTC, merged