0.9.10
united-manufacturing-hub/united-manufacturing-hub pull request #1379
Opened 2022-12-12 09:13 UTC by DaruZero

# Description

### Features

- HiveMQ instead of VerneMQ
- OPC/UA simulator
- tulip-connector API
- Multiple custom tag splitting in Grafana

### Chores

- Upgraded various dependencies

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

- [ ] Installing a new instance
- [ ] Upgrading an old instance
- [ ] Complete data workflow

# Checklist:

- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding changes to the changelog (if needed).
- [ ] I have made corresponding notices to the upgrade instructions (if needed)

# Changelog changes

*wip*

# Upgrade instructions

*wip*

2022-12-12 13:48 UTC, DaruZero commented
Ready to merge 🚀 
@Scarjit @JeremyTheocharis

2023-01-20 14:14 UTC, Scarjit commented
WIP

2023-01-30 16:01 UTC, JeremyTheocharis requested changes

2023-01-30 16:01 UTC, JeremyTheocharis commented on golang/internal/kafka.go
> +				NumPartitions: 1,
istn standard behaviour 3?

2023-01-31 09:03 UTC, Scarjit commented on golang/cmd/mqtt-kafka-bridge/kafka.go
> +		if json.Valid(payload) || strings.HasPrefix(kafkaTopic, "ia.raw") {
https://github.com/united-manufacturing-hub/learn.umh.app/pull/203

2023-01-31 10:26 UTC, Scarjit commented on deployment/united-manufacturing-hub/templates/barcodereader/deployment.yaml
> +            - name: MICROSERVICE_NAME
https://github.com/united-manufacturing-hub/learn.umh.app/pull/204

2023-01-31 10:26 UTC, Scarjit commented on deployment/united-manufacturing-hub/templates/barcodereader/deployment.yaml
> +            {{if .Values._000_commonConfig.debug.enableFGTrace}}
https://github.com/united-manufacturing-hub/learn.umh.app/pull/204

2023-01-31 10:26 UTC, Scarjit commented on deployment/united-manufacturing-hub/templates/customMicroservices/statefulset.yaml
> +            - name: MICROSERVICE_NAME
https://github.com/united-manufacturing-hub/learn.umh.app/pull/204

2023-01-31 10:27 UTC, Scarjit commented on deployment/united-manufacturing-hub/values.yaml
> +  rawMessageLRUSize: 100000
https://github.com/united-manufacturing-hub/learn.umh.app/pull/204

2023-01-31 10:39 UTC, Scarjit commented on deployment/united-manufacturing-hub/templates/kafkatopostgresql/deployment.yaml
> +              name: fgtrace
Done. "How to use fgtrace"
Currently set to internal

2023-01-31 12:34 UTC, JeremyTheocharis approved these changes

2023-01-31 12:54 UTC, Scarjit approved these changes

2023-01-31 12:54 UTC, merged