0.9.12 prerelease2
united-manufacturing-hub/united-manufacturing-hub pull request #1525
Opened 2023-03-31 11:34 UTC by Scarjit

Supersedes #1524

2023-03-31 12:05 UTC, DaruZero commented
we need to add backwards compatibility for redis

2023-04-04 08:41 UTC, JeremyTheocharis requested changes

2023-04-04 08:41 UTC, JeremyTheocharis commented on deployment/helm-repo/index.yaml
> +    - https://0-9-12-prerelease2.united-manufacturing-hub.pages.dev/united-manufacturing-hub-0.9.7.tgz
remember to change back

2023-04-04 08:41 UTC, JeremyTheocharis commented on deployment/united-manufacturing-hub/Chart.yaml
> +version: 0.9.12-prerelease2
remember to change

2023-04-04 08:43 UTC, JeremyTheocharis commented
Please also look at the automated tests, which are failing atm

2023-04-04 13:06 UTC, closed without merging