Remove unused dependencies
united-manufacturing-hub/united-manufacturing-hub pull request #1723
Opened 2024-01-22 16:04 UTC by Ayato77

- Unused dependencies in go removed by go mod tidy are removed
- Dependency of deprecated microservices in dependabot is already removed

close united-manufacturing-hub/MgmtIssues/issues/1483

2024-01-23 14:09 UTC, JeremyTheocharis requested changes

2024-01-23 14:09 UTC, JeremyTheocharis commented on Makefile
> +# Copyright 2023 UMH Systems GmbH
Where is this file coming from?

2024-01-24 10:36 UTC, JeremyTheocharis approved these changes

2024-01-26 16:45 UTC, Scarjit approved these changes

2024-01-26 17:20 UTC, merged