Json schema docs
united-manufacturing-hub/united-manufacturing-hub pull request #347
Opened 2021-07-21 17:24 UTC by Gornoka

add openapi doc for mqtt json objects

2021-07-21 17:30 UTC, JeremyTheocharis requested changes

2021-07-21 17:30 UTC, JeremyTheocharis commented on docs/content/en/docs/Concepts/mqtt/index.md
> +
Can we remove the changes in this file?

2021-07-22 13:20 UTC, Gornoka commented on docs/content/en/docs/Concepts/mqtt/index.md
> +
changed

2021-07-22 13:21 UTC, JeremyTheocharis approved these changes

2021-07-22 13:22 UTC, merged