Changed authors
united-manufacturing-hub/united-manufacturing-hub pull request #378
Opened 2021-07-27 12:09 UTC by JeremyTheocharis

@all: Please check whether this mention is fine for you

2021-07-27 12:25 UTC, Scarjit requested changes
Lukas should have an email adress

2021-07-27 12:51 UTC, JonaVo requested changes

2021-07-27 12:51 UTC, JonaVo commented on AUTHORS
> +- Jonathan Vossen <jonathan_vossen@mckinsey.com>
- Jonathan Vossen <jonav@gmx.de>

2021-07-27 14:25 UTC, Gornoka commented on AUTHORS
> +- Jonathan Vossen <jonathan_vossen@mckinsey.com>
lukas.hennies@rwth-aachen.de

2021-07-27 14:29 UTC, Scarjit approved these changes

2021-07-28 18:27 UTC, larswitte approved these changes

2021-07-28 20:54 UTC, Gornoka approved these changes

2021-07-29 08:09 UTC, JonaVo approved these changes

2021-07-29 16:17 UTC, merged