feat: removed old grafana plugins folder
united-manufacturing-hub/united-manufacturing-hub pull request #381
Opened 2021-07-27 15:30 UTC by Scarjit

Fixes issue #380

2021-07-27 18:17 UTC, JeremyTheocharis requested changes

2021-07-27 18:17 UTC, JeremyTheocharis commented on .idea/.gitignore
> +# Default ignored files
IntelliJ is back :D

2021-07-28 08:13 UTC, Scarjit commented on .idea/.gitignore
> +# Default ignored files
Resolved in cba6dcb

2021-07-28 08:29 UTC, JeremyTheocharis approved these changes

2021-07-28 17:25 UTC, merged