Added documentation for product shadow
united-manufacturing-hub/united-manufacturing-hub pull request #382
Opened 2021-07-27 16:09 UTC by larswitte

Fixed #357

2021-07-28 06:16 UTC, JeremyTheocharis requested changes

2021-07-28 06:16 UTC, JeremyTheocharis commented on docs/content/en/docs/Concepts/Digital Shadow/index.md
> +weight: 2
You can remove the weight here

2021-07-28 06:16 UTC, JeremyTheocharis commented on docs/content/en/docs/Concepts/Digital Shadow/index.md
> +TEMP: [count](#count)
Should be removed :)

2021-07-28 06:16 UTC, JeremyTheocharis commented on docs/content/en/docs/Concepts/Digital Shadow/index.md
> +
Very detailed guide! Perfect!

2021-07-28 17:59 UTC, HW138 approved these changes

2021-07-29 16:26 UTC, larswitte commented
Please merge, it's finished.

2021-07-29 16:30 UTC, merged