455 improve guide connecting machines and creating dashboards
united-manufacturing-hub/united-manufacturing-hub pull request #678
Opened 2021-11-22 13:18 UTC by oarne97

2021-12-03 09:59 UTC, kruegeralex commented on docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/index.md
> +UMH Hub has a wide range of ports and connectors.
The United Manufacturing Hub has a wide variety of connectors and therefore offers maximum connectivity to different machines and systems.

2021-12-03 09:59 UTC, kruegeralex commented on docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/index.md
> +{{< imgproc logos_data_sources Fit "800x800" >}}{{< /imgproc >}}
This cross out. And the subline "could contain sensitive information".
It is best to use "www.draw.io" for the graphic.
Insert the Weihenstephaner standard logo and the logos from our website in a "chaotic order".

![WS](https://user-images.githubusercontent.com/77407527/144581210-7f3b051e-1f43-4633-bc9a-01f4e03f52b6.png)
<img width="249" alt="image" src="https://user-images.githubusercontent.com/77407527/144581303-c22d98a5-12cc-46ee-9574-a5bdffaf1889.png">

2021-12-03 09:59 UTC, kruegeralex commented on docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/index.md
> +These are:
Here are a few selected examples

2021-12-03 09:59 UTC, kruegeralex commented on docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/index.md
> +## 2. Node-RED
```suggestion
## 2. Extracting and preparing data with the help of Node-RED
```

2021-12-03 09:59 UTC, kruegeralex commented on docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/index.md
> +In the following, the procedure for creating a Node-RED flow is described in detail using **two examples**. The first example is about a cutting machine which will be retrofitted by external sensor t
```suggestion
In the following, the procedure for creating a Node-RED flow is described in detail using **two examples**.

1. Here we will retrofit a cutting machine with the help of external sensors.
2. In the second example, we will use OPC/UA to read a warping machine data directly from the PLC.
```

2021-12-03 09:59 UTC, kruegeralex commented on docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/index.md
> +- Button Bar
```suggestion
- Button Bar
```
```suggestion
- Light Barrier
- Button Bar
- Capacitive sensor
```

2021-12-03 09:59 UTC, kruegeralex commented on docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/index.md
> +*1. Connect Sensors*
```suggestion
#### 1. Connect Sensors
```

2021-12-03 09:59 UTC, kruegeralex commented on docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/index.md
> +*2. Make the connected sensors visible to our system*
```suggestion
#### 2. Make the connected sensors visible to our system
```

2021-12-03 09:59 UTC, kruegeralex commented on docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/index.md
> +*3. Creating a flow*
```suggestion
#### 3. Creating a Node-RED flow*
```

2021-12-03 09:59 UTC, kruegeralex commented on docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/index.md
> +In Node-RED basically three pieces of information must be communicated to the system.
In order to contextualise the resulting data points with the help of the United Manufacturing Hub, 3 identifiers are necessary:

2021-12-03 09:59 UTC, kruegeralex commented on docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/index.md
> +- The customer ID to be assigned to the asset: *customerID*
```suggestion
- The customer ID to be assigned to the asset: *customerID* (Default value for the development setup "factoryinsight")
```

2021-12-03 09:59 UTC, kruegeralex commented on docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/index.md
> +- The location where the asset is located: *location*
```suggestion
- The location where the asset is located: *location* (Can be chosen freely)
```

2021-12-03 09:59 UTC, kruegeralex commented on docs/content/en/docs/Getting started/connecting-machines-creating-dashboards/index.md
> +- The name of the asset: *AssetID*
```suggestion
- The name of the asset: *AssetID* (Can be chosen freely)
```

2021-12-14 10:20 UTC, kruegeralex commented
Hi @oarne97 

thanks for your input so far.

Akuell still further remarks:
- I would make it clearer that step 3.1 and 3.2 are the same for all Sebsonren and then different for everything that reads not so good.
- Add a disclaimer (best under the button bar) that the system must still be added analogous to our data model layers.

2021-12-15 08:38 UTC, kruegeralex commented
@Scarjit

2021-12-15 11:24 UTC, oarne97 commented
@kruegeralex

2021-12-15 12:42 UTC, Scarjit approved these changes

2021-12-15 13:32 UTC, JeremyTheocharis requested changes
Let's spellcheck it and try to format it better for the eyes, e.g., prevent unnecessary bold texts, consistent use of headings, etc.

2022-01-18 16:34 UTC, JeremyTheocharis approved these changes

2022-01-20 08:31 UTC, merged