docs: update digital shadow documentation
united-manufacturing-hub/united-manufacturing-hub pull request #714
Opened 2021-11-25 17:44 UTC by JeremyTheocharis

Fixes #501

2021-11-25 17:46 UTC, JeremyTheocharis commented
@RobertFeldmannMck You are working on using Digital Shadow to integrate Quality Labs, right? I am currently reworking the official guide and it might help your understanding: https://deploy-preview-714--umh-docs.netlify.app/docs/concepts/digitalshadow/

2021-11-26 18:14 UTC, larswitte requested changes
Thank you Jeremy, I like the new structure a lot.
I only found small spelling stuff.

2021-11-26 18:14 UTC, larswitte commented on docs/content/en/docs/Concepts/mqtt/index.md
> +| [`uniqeProductAlternativeID`](/docs/concepts/mqtt/#explanation-of-ids) | int | In short: AID. Used to describe a single product of the type [`product_id`](/docs/concepts/mqtt/#explanation-of-ids) i
This is the ID that might be written on the product (with a physical Label, lasered on to it etc.: technologie independant) and is usually the relevant...

2021-11-29 17:19 UTC, JeremyTheocharis commented
Ready for review. I've created #718 to consolidate everything as it does not make sense to work on this PR anymore. Nevertheless, this PR improved the current state and therefore should be merged.

2021-11-29 17:23 UTC, Scarjit approved these changes

2021-11-29 17:51 UTC, merged