0.9.0 prerelease3
united-manufacturing-hub/united-manufacturing-hub pull request #979
Opened 2022-04-19 15:44 UTC by Scarjit

# 0.9.0 prerelease3

Contains fixes for prerelease 2
Supersedes #974

2022-04-19 17:02 UTC, JeremyTheocharis requested changes
let's change the default installation script in development.yaml by removing `--devel`. Then we can also push this prerelease to main.

2022-04-19 17:02 UTC, JeremyTheocharis commented on docs/static/examples/development.yaml
> +      if ! helm repo add united-manufacturing-hub https://deploy-preview-979--umh-helm-repo.netlify.app/ ; then
see other note

2022-04-19 17:20 UTC, Scarjit commented on deployment/helm-repo/index.yaml
> +    - https://deploy-preview-979--umh-helm-repo.netlify.app/factorycube-edge-0.7.0.tgz
Resolved in commit below

2022-04-19 17:20 UTC, Scarjit commented on docs/static/examples/development.yaml
> +      if ! helm repo add united-manufacturing-hub https://deploy-preview-979--umh-helm-repo.netlify.app/ ; then
Resolved in commit below

2022-04-20 10:59 UTC, JeremyTheocharis approved these changes

2022-04-20 10:59 UTC, merged