Added microservices to calculate state from activity
united-manufacturing-hub/united-manufacturing-hub pull request #988
Opened 2022-04-21 14:03 UTC by Scarjit

# Description

This pr adds a microservices, calculating state from activity and detectAnomaly

Fixes #987 

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- [ ] Send activity messages and check if state messages are send
- [ ] Send activity messages and check if detectAnomaly messages are send

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked that my issue complies with the [Contributing guidelines](https://github.com/united-manufacturing-hub/united-manufacturing-hub/blob/main/CONTRIBUTING.md)

2022-04-21 14:04 UTC, Scarjit commented
TODO: Add Helm chart related files and GH workflow

2022-04-22 12:57 UTC, JeremyTheocharis requested changes

2022-04-22 12:57 UTC, JeremyTheocharis commented on golang/cmd/kafka-state-detector/activityKafka.go
> +			stateMessage.State = datamodel.UnspecifiedStopState
ensure that this is only applied when activity changes and not when someone sends repeatedly the same activity=false message.

Reason: we do not want to overwrite a "detectedAnomaly state" with a "duplicated activity=false and therefore state UnspecifiedStopState message"

2022-04-22 12:57 UTC, JeremyTheocharis commented on golang/cmd/kafka-state-detector/activityKafka.go
> +			stateMessage.State = datamodel.UnspecifiedStopState
deduplication with checking timestamp and activity from latest activity (you already have that function somewhere)

2022-04-26 08:32 UTC, JeremyTheocharis commented on golang/cmd/kafka-state-detector/activityKafka.go
> +			stateMessage.State = datamodel.UnspecifiedStopState
did you worked on this? i am not seeing any commits

2022-04-26 17:03 UTC, JeremyTheocharis approved these changes

2022-04-27 08:41 UTC, JeremyTheocharis commented
@Scarjit: best is if you merge this PR, i am too unsure about messageprocessing.go (whether to keep it or remove it)

2022-04-27 13:10 UTC, Scarjit commented
This should be merged after #1014

2022-04-27 14:09 UTC, merged